apiVersion: v1
kind: Secret
data:
    admin-token: ENC[AES256_GCM,data:uuiovFUe0us3sLN1i9k16olC3RuJx/82Nl0KTKbaTPj8R/YqvlfGxZPfE7KdFO1PhIDVleMyaAC8y4V7h8V29JvElplerKRvgXawowMdF8AxcEVHuZVx6Q==,iv:xrAbIjxDFkqj4UaRL9O8EsWVD6BY0xehhd+JwttOZ9Y=,tag:cxCUc4uZwJcf8Q+6EJ66LA==,type:str]
    yubico-client-id: ENC[AES256_GCM,data:a/jN1tjJo2A=,iv:5rqyVxVq1ekxqR3nO+9lbVebUbCag2H1U+LDdRS3dfE=,tag:ebbSnzB2hP4CxZT3/i0GBg==,type:str]
    yubico-secret-key: ENC[AES256_GCM,data:rRe1+KLc4p2vKG1nc8ZudMayNUdXQ8NNJfO1f6YjUQ0kMe5f,iv:xcvnMKtED7sYHnIyOqJPBM+NdS6BNVQwREV3OkmBxwU=,tag:sHlbJ+zYzjMFy4K1dtKn6w==,type:str]
metadata:
    name: vaultwarden
    namespace: vaultwarden
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1099kpzqp5v429mcyekxxnnyfkyuqxgq3esxvamc0kv7tf7nh9g9qymcpmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneEhFRGxWdWdqZXpiYzd5
            ejhoOWhTZGVIMmhPSDJra0lRU2Q5VWs3d2pFCnBMZEFpc2lZdVVaUjh0elA2UGlt
            VkNKdGpaNEVBb251SmhaYVdvVzZZZ0UKLS0tIExJNXFIOG9SOWtaSXlCcjRPTVJW
            My9JRm00SjRxTUl1RVJtL1ZDU3RXQzAKyBet23MUP4yY81WxNR1Bm5HxQiVkbCvM
            PHGy8yuos5Y0gY0t/IC+nqUOSbyHd1QMrSnJ2uvqO6B14s4y5WSMtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-09T21:13:03Z"
    mac: ENC[AES256_GCM,data:gEM6Fv+5yVIKslaC23rrkvjl2iTGiKSP7uo3orPdviPd6BGfxZYXz9dmbIA8teyi8pa1eUocCc0DogFN/NDICeTQeEtvfNXC8d+IvZqr07hTLxOlo7fzc0Q4lYdBNAGLWv1gu9pcSKcil1se3QR2rLjKPtOrSKRwSA1irqSskNQ=,iv:o+cBGdNUOu318OHb6oP1G62f0F8fynuYcE4uxhByqSY=,tag:c5HE6DJhLALQKvU98qlmsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
