apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: sz-service
  namespace: flux-system
spec:
  image: ausraster/sz-download
  policy:
    numerical:
      order: asc
  interval: 1m0s
  secretRef:
    name: docker-hub