{
 "title": "Basic metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Memory usage in %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[2m]) + avg_over_time(node_memory_Cached_bytes[2m]) + avg_over_time(node_memory_Buffers_bytes[2m])) / avg_over_time(node_memory_MemTotal_bytes[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage in %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Logs",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Logs for ${namespace}",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "repeat": "namespace",
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |= ``"
    }
   ]
  }
 ]
}