apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: immich
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:+FHI0ZxcncKZnjPn7rpNNaNWdgvjP1EFRugLFgJFZWFqsntsY6IbfA==,iv:Naa7bIOT9sgVAeuw1G8F0tIDM/8xIdPCQkJYhfl6caE=,tag:E2UFLdRk7l4jltb381lMvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OVhBd2JDR2JTSWg5WkJ6
            L1UzVEZDUzJ3ZWl0SURrTk1jRkkvdi9va2k0ClhxNWorazhKUUozMzJXdmVrWloz
            R0tVYXluQXd4blVXWHFCWkd3d0tjSE0KLS0tIDZ4K0FsSUNHaFU3aTBNbEtvandG
            ekE1cTNTUHJldnl1TmxQR1NJcW54a2MKu0i9ilvnePOhSd9itwKrwFPVm7wwtHx2
            tAZWi9sNLUNe5lwydDO0Sc9TQhU8VsmJOfCMZ3CaR8GL6SP6ZdaA1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1099kpzqp5v429mcyekxxnnyfkyuqxgq3esxvamc0kv7tf7nh9g9qymcpmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T10:24:06Z"
    mac: ENC[AES256_GCM,data:Rbmrvfu9ZEVQz1ndT7VYxDis2ertJ92/3CTOKtblqHMgtRZVO8tsfr6dQDbunmfVYm9+6HSLX0lntGQ1SHsdcjx3BuorjQLQFcOC/BGMbdrz9QqLt6ld2tIE1HtEQgouhiER12LEWwsgYILipb4bY0EEKsd4czfsILZSfArVWsE=,iv:qPHkgUK3UYqCy9GtG2hsQ9ifg9XoUEHUAe/XgcqT7+M=,tag:s0FnGFVpVkXnm9m99RZqcg==,type:str]
    version: 3.13.3
