apiVersion: ENC[AES256_GCM,data:bdc=,iv:A9sfYlWPaMY7T/A8oNjF52P3eE1CRdkaLFANrbkVRw0=,tag:ks6zAerGma+hRHRJORhxGQ==,type:str]
kind: ENC[AES256_GCM,data:ld9ACe0y,iv:3O03beILDVpYCAvhpFEKDXuLKHvB/e74QWfjb4scFqA=,tag:wkU8HbkbCMXMJHnEwAPrXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jb7ZzKeqS/SaQOH5iPlZ/PO3,iv:BtsqJ0QsJxp81qdW/KcSTA5MrknA/1geAzQUWSfRCCM=,tag:4Evl4y2t/TUwmABJ45/6aA==,type:str]
    namespace: ENC[AES256_GCM,data:Hm5WxTnCNJetfhnzM0n+r0ie,iv:7/sA6cSDivvHg/xjKThCyki/n7YjQlmLcpOJ2bD0nn4=,tag:FI6/eGKpu7a8X63/+FPHqA==,type:str]
type: ENC[AES256_GCM,data:tqGZl12k,iv:6gl0n7GUK1V5ykb0HkeVzIvBTEj+iiFo1T3HSmP92EI=,tag:H3JoVnHvU/vhJNj/Qt6QFQ==,type:str]
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:+SGb6mxDsoghjlnRM8x7QCq+b5GVpQq2fduYC3DhLfuBPO0uye3EVSuJZZLskA==,iv:8retyGrpfZ5H7/+uVpY7H0G4pDu9LzZIPXqieIPqj/Q=,tag:5VMVHBDopV/eg9YiyddxVg==,type:str]
    BOT_ADMINS: ENC[AES256_GCM,data:9K7UsdDH0u4=,iv:96cA6do6cr64/UsfJu6WnFMoH1OHZVe32UaCrAebFXE=,tag:4zX0QAXLm+us8nEqlySKww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2djFBWGNVSEFNYmFNVERP
            Nmo2UWlIcHZRRmt3eGR0S21WeG1yTU5yM0JFClNwbTByb2duQklyTzRQSUozekVL
            VGdmUGR1NlZGYmJKcEEwMEsxMzhpSTgKLS0tIEIycmJJTEpKeGx5eTJUR3FOdFhT
            Y2JIR0tLQkdXYTZSOGN0ci9JTmRjencKDxnAL61tKgTNOyRDHWmFfdpNQvP97XG5
            Zwf71igzSAuL9GUHQBEMb41QBixVUsEZ4khsC9JRCV1Ax9LWnBZwRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1099kpzqp5v429mcyekxxnnyfkyuqxgq3esxvamc0kv7tf7nh9g9qymcpmx
    lastmodified: "2026-07-07T21:05:51Z"
    mac: ENC[AES256_GCM,data:USdLsRJuwwflwQYUknTCNPsCMzXzEV83e8kk/MEGibcHeWr/2AN3Dzn3BY+TF6i+IjNSX1mOMrqLGheq+VkTmPubcU6vW4B/6hHjcNpvJmrUKnIsBbaRpgm6Oo1xQzVsPIXLgAnNYxkSqrD8ceJuyXPfHIdLCiaFZ9L1U8USYzQ=,iv:kgE7ehDb4enlBaC+QcYYUFfoeQtmvnsFeZKmHqLFf00=,tag:sJRN+cQZj51y5eh6P1X75A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
