apiVersion: ENC[AES256_GCM,data:FnE=,iv:NQyXIM2vPK5j7KmUu7+oWdRxw68Q/oJY6cB5JR985oM=,tag:YdBxwCRRK4HiSAjV/SrGdQ==,type:str]
kind: ENC[AES256_GCM,data:wthZbhq1,iv:mNU4PgTu+YRdiIZkGEUZkAu7Zo9lllCLjWIEvvmR2gA=,tag:eha1G/u5AeCzVSfKJXQrKg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SUvXqF3pYXKgQyRIoH/0S9SV,iv:db2JxxweyY9IMqmTgxTxaEumwJWJ85HpxyBqRkeqejg=,tag:0BM5hSL/oblG9HMTFmzDcQ==,type:str]
    namespace: ENC[AES256_GCM,data:6ghsp/XSN42SmMFLaGJa2okb,iv:JXToIkietB4dzLtDdgykOrxMTslXcmc6CfTV5qrCxPw=,tag:fZY5UMPDZWZCZgDXvHoDMA==,type:str]
type: ENC[AES256_GCM,data:jkpRkxW4,iv:U44ieb9mwTBUP51vnaZ3Xga0ucSjCX9qmzZC1T4CJyY=,tag:i2E78nrzonsxkASH2jv/rg==,type:str]
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:e6VHEy2MqoPk4LcknOeZagwTpdxp1ApdhOH3kTWU7qZz8UJWPyAqTGQP/ueCyQ==,iv:JwGy+p3m1B1d/hNLSpl7lG+oXeANKNE7I02yJYcdshc=,tag:hySUuy3lOWqCN1iiF/4KkQ==,type:str]
    BOT_ADMINS: ENC[AES256_GCM,data:dqxt/RXvEUE=,iv:XHmBiJnYKhYTbDvQmzxX4CsF5kaQg90g7GGefkCcDG0=,tag:eDkX7X28g8aRL22ELcjoGg==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMUp4UGhPQkkyeDhmVjZW
            MVJrRnlDcWhOdHp4MlRuTG5LMyt4eFlicWpVCnpiYjBVNWpLZk1LbzBqM3Q5YmRr
            VkhIN0lLU2RtNWUxaHdQbVZXRk1JQlEKLS0tIHJzbXlycFlocThOcnlxNjF2U05s
            TUZDa3lFZ1hPNEZRc2Y2U1MxQUtoTncKEW/yxzmhUEHDkZ83NA1lU4J32iPINQKv
            wD7TotU4Vs/Yw02CQcIcQ2jddMVNRPdkRjil8wXVMFT9XJu5Dq0Bpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1099kpzqp5v429mcyekxxnnyfkyuqxgq3esxvamc0kv7tf7nh9g9qymcpmx
    lastmodified: "2026-07-07T20:36:34Z"
    mac: ENC[AES256_GCM,data:kthIHPFne9QeTf1Zl1yrofPIUf0LeMUMhdAY82Weomx/BfadGVOl4QfUsfm0+7vdQXGI0MYG/InwFt1wDNQd3cuIFbjUqIMFP3NEcXxli7CepOcYYXZMiog4kmHtzTeTZhUZZJeXFexlrvki7yOX8rAaz5y+Ckyf4xoyCSFH8Vs=,iv:i9pMYQUwZ+WLaXXkTB4kC5oY8ASw/B9b2ywDL2Z9/Rg=,tag:JBICwv5sphQN0HHHC64MEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
