apiVersion: ENC[AES256_GCM,data:XGk=,iv:z4WreAxKCyLMtLy4YejFUtIvQlFH4eTDzNI0fejj3RY=,tag:PlQpfWLTV78vMFsKTOvqOA==,type:str]
kind: ENC[AES256_GCM,data:EkUPcxX2,iv:j0EleXNUy9huQaq2IraFcLrI193BDnWiq72Ixup5BOI=,tag:b4vR+TfuqWS1iwRKQ9kP0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KMPKfFrPbQ==,iv:xQfr8AjXvj0b/jcFBwwUnTAP45w1pfn4d2b3yXtlEd8=,tag:JUsQRJfVbKRceIkjLGz17Q==,type:str]
type: ENC[AES256_GCM,data:0GjIHunlUJsiSeQSZLll/c5XNpK44e26,iv:a6nn8vPITNLLWj5tHtVLM8tl4v5AqWZtV6cnH6HJrFQ=,tag:qhJZawdh2AIqd0xcUtNnoQ==,type:str]
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:lofSYC6tKywnhZj/SzwcTKHd7rHoFMlY/WEsfkDnO8kdDVGMlqleyZc/T32H4fVIxATqK3bdq+Q=,iv:5w+Ddru/dV3Jdw/4aupjQiEMpNsNCvbevn0aXMITafI=,tag:vL28U69g43Pt/fXZ8cfZSA==,type:str]
    #ENC[AES256_GCM,data:tcD+TtZK,iv:cGr9AFV7lTNnD253zX4wyXZyOLAB+hs1WaYXGve+kNQ=,tag:e8ash7Sv1cqj9IHIzo8EBA==,type:comment]
    RESEND_API_KEY: ENC[AES256_GCM,data:Un9KwIgKq9x4G1nCYGGfVL+EkAiZw7noWpz6ZfVQo/lLTbai,iv:uYWcGkUVq0ZsD8Rg+618yk/EOU6g7QXc/dbmsPEZNkE=,tag:Mvw3Py8+fxOql6f/kpn+sg==,type:str]
    #ENC[AES256_GCM,data:ya03cjXVSBc3sP0yf5wUSEtA1g==,iv:QhSrDQPkzGGyxVHohLBonblEyy6w1UsKRZRbgRcY0FU=,tag:/bb1jbAUCPEJv5JLjSmReA==,type:comment]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:FLqtzijoPUbiIeWpw+AMQ58czUt5cXUIfqRcbBbgQT4n4+m9DicA25UJ/MHjOU/dlohVrDVpP1UCFMal36QsZ0kQdqEKclw=,iv:wNf3646/g4dBrkaL4oht4G7EWB1Rdc33Prsp+7Hhix4=,tag:l7MyO2Q5qNVzDYFUjEkCxw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:1ctSrHC4NY3aTxiRKclENAgKC/s8Me7mKirmfT9akGS3zfA=,iv:Oqj47OGD0F3TgWyrK53nzl91bG/1Fkwtj+UsVEFzUGE=,tag:yoTXXazpjau1FAfL4T7+8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1blUyUnJ2a1dqN1Q4bzFo
            TC9ldFNrMytQQ28rSGdSM0tUZElEVU9mdG1VCndvN1BOdldOZVNlTlJzOXFPV3lH
            ZVpEYmMxbVZIQjFoaDl1R0dtcGMrS2MKLS0tIDQ2Q3o2NkE0eTU2aFQyWHY4ZldV
            cjNVeXNiL1JidGh4WExvcnBBVXFwMlUKZTJ5mJEvJ2acwIzkL3cI6Ro4wQRE2iKa
            Q3gBm2K5FRxj/heXChrczIyUiWml31y+QYf/WwD9HV+SMc2p2aR0GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1099kpzqp5v429mcyekxxnnyfkyuqxgq3esxvamc0kv7tf7nh9g9qymcpmx
    lastmodified: "2026-05-11T09:37:39Z"
    mac: ENC[AES256_GCM,data:dNmFuFfQaWqzWVxiPUM33c5AmML3YWewHXC9hESp2xx6ODy4Dr1aJwDRdwqxPjgPqNBUweqaY1qnMbkHSPHhRygCKkb7enow3fSWimgaA6AwDcMLXdh62lDAE0b8qKs3d9ixnbVs+dCcR/LwM4nQ3rGtUFhBfA6r5DZ24AEVCqU=,iv:Jgj7CrnCodbFXhr1f3L8mOP818Vtqmp4w1iyKM19xTw=,tag:guFN9p6/pFA6J0Awqdldpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
