apiVersion: ENC[AES256_GCM,data:XGk=,iv:z4WreAxKCyLMtLy4YejFUtIvQlFH4eTDzNI0fejj3RY=,tag:PlQpfWLTV78vMFsKTOvqOA==,type:str]
kind: ENC[AES256_GCM,data:EkUPcxX2,iv:j0EleXNUy9huQaq2IraFcLrI193BDnWiq72Ixup5BOI=,tag:b4vR+TfuqWS1iwRKQ9kP0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KMPKfFrPbQ==,iv:xQfr8AjXvj0b/jcFBwwUnTAP45w1pfn4d2b3yXtlEd8=,tag:JUsQRJfVbKRceIkjLGz17Q==,type:str]
    namespace: ENC[AES256_GCM,data:i7oUC5YfgGPnrYFa6Q==,iv:bmBhXlzcZqRXhssMc7Izw8Jz1tM+A8K8O48Lq6LnngQ=,tag:dzhuTgL4tzS0H+1pjl/24Q==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Di6sux74fY6yhD727nYxiTproP3Y/00bwOB1jQ==,iv:9p0r5eExOwQXvUUHpS8s64Rj3/O+aLsIV28oiyckfKk=,tag:BBUeiLWvVAmnmonUbS5uug==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:lofSYC6tKywnhZj/SzwcTKHd7rHoFMlY/WEsfkDnO8kdDVGMlqleyZc/T32H4fVIxATqK3bdq+Q=,iv:5w+Ddru/dV3Jdw/4aupjQiEMpNsNCvbevn0aXMITafI=,tag:vL28U69g43Pt/fXZ8cfZSA==,type:str]
    #ENC[AES256_GCM,data:tcD+TtZK,iv:cGr9AFV7lTNnD253zX4wyXZyOLAB+hs1WaYXGve+kNQ=,tag:e8ash7Sv1cqj9IHIzo8EBA==,type:comment]
    RESEND_API_KEY: ENC[AES256_GCM,data:Un9KwIgKq9x4G1nCYGGfVL+EkAiZw7noWpz6ZfVQo/lLTbai,iv:uYWcGkUVq0ZsD8Rg+618yk/EOU6g7QXc/dbmsPEZNkE=,tag:Mvw3Py8+fxOql6f/kpn+sg==,type:str]
    #ENC[AES256_GCM,data:ya03cjXVSBc3sP0yf5wUSEtA1g==,iv:QhSrDQPkzGGyxVHohLBonblEyy6w1UsKRZRbgRcY0FU=,tag:/bb1jbAUCPEJv5JLjSmReA==,type:comment]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:FLqtzijoPUbiIeWpw+AMQ58czUt5cXUIfqRcbBbgQT4n4+m9DicA25UJ/MHjOU/dlohVrDVpP1UCFMal36QsZ0kQdqEKclw=,iv:wNf3646/g4dBrkaL4oht4G7EWB1Rdc33Prsp+7Hhix4=,tag:l7MyO2Q5qNVzDYFUjEkCxw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:1ctSrHC4NY3aTxiRKclENAgKC/s8Me7mKirmfT9akGS3zfA=,iv:Oqj47OGD0F3TgWyrK53nzl91bG/1Fkwtj+UsVEFzUGE=,tag:yoTXXazpjau1FAfL4T7+8Q==,type:str]
    #ENC[AES256_GCM,data:WrVfNcKVAedKkasidNWzbw==,iv:9aavcDWrPCp4clOS4i8XsZqdLb4UZK3LzpQe3SDBV+I=,tag:xuxNwNr1bczxzI8/MZQHtg==,type:comment]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:5wNxk0+/HtI9UmCZzlKT/y2uRNk=,iv:xAMwo0v9trb/0KShEscZsSYbY8YVgisDu1rGsvf/rfE=,tag:b5SrYwRqCS8FFmO1uPH4qw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HE0HdD8J0bgIM6Whcpb7riNY4O/YvkPeXNkcV0JT3laNbfeqacMwJQ==,iv:82ogZWDQsP1dgFjgO1Jp/p7TRPYz39oBgF5EsfqrI2M=,tag:Aywid5axrqpISKsj+mmD3g==,type:str]
    S3_BUCKET_NAME: ENC[AES256_GCM,data:m/GslPF2ME2QcF21F0ASvZwskksr7EQfwA==,iv:UlmQT/YxeUIge/4osX1pWdOwf5Uyjk8J6tCZ+4yj5bI=,tag:zvk4yMwuWsPWAGGVAhklHg==,type:str]
    S3_REGION: ENC[AES256_GCM,data:AiItQGpyClhQbNyp,iv:ZLK3KJUllUZ9vLgM7rTAX80/5d+AbbjIrJ3u+JZihbA=,tag:uo7/EHuiHJr0UwOFf+bKug==,type:str]
    #ENC[AES256_GCM,data:3sLM8+rR8q+Uyd0=,iv:h9mKyHCRbYNzzNG7700fx1PIhQhOSIltNKSty11dia4=,tag:48mW5w3Ta88+M9r6pMQ9JQ==,type:comment]
    TURNSTILE_SECRET_KEY: ENC[AES256_GCM,data:8xpdwFZPt3XXXfpYRJCOAA2+sdWTzxoTMBATcc0JEamB558=,iv:MbxWsEAT0jympSg4JEnCM0Fhgg1r+/I8NkU75mBU7so=,tag:71tTaByhteHFSGjhlkkrzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1blUyUnJ2a1dqN1Q4bzFo
            TC9ldFNrMytQQ28rSGdSM0tUZElEVU9mdG1VCndvN1BOdldOZVNlTlJzOXFPV3lH
            ZVpEYmMxbVZIQjFoaDl1R0dtcGMrS2MKLS0tIDQ2Q3o2NkE0eTU2aFQyWHY4ZldV
            cjNVeXNiL1JidGh4WExvcnBBVXFwMlUKZTJ5mJEvJ2acwIzkL3cI6Ro4wQRE2iKa
            Q3gBm2K5FRxj/heXChrczIyUiWml31y+QYf/WwD9HV+SMc2p2aR0GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1099kpzqp5v429mcyekxxnnyfkyuqxgq3esxvamc0kv7tf7nh9g9qymcpmx
    lastmodified: "2026-05-16T19:48:29Z"
    mac: ENC[AES256_GCM,data:S48+1aJxlWAiTwgQHSC4cEAUQ0WcVf7wJ/UJndB0tvsxRD4K0iJzdpHTQvilYv5SAcaDFqOmP2K03o1rZW5w6lbn6doXMsHSI8zatV/I0fFJrJY18x4TGv5o8u/VygFtoEjCWkuu7/wuc1tBdL3xs/pMthtP7KLht92d1DauPTc=,iv:kIz7KMFSDgjF6QaMN+yVAehEg5t4976x8Mdmivdf0W8=,tag:fcDGBidOPs1nM2X3HZZtGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
