---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sessionhoster-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/internal/sessionhoster/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - homeserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sessionhoster-pvc
  namespace: sessionhoster
spec:
  storageClassName: local-storage
  volumeName: sessionhoster-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi