apiVersion: v1
kind: Secret
metadata:
    name: umami-config
    namespace: umami
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:hz0dT4DPOcQ0zq5CbRV1L4t5Yzr7im9dDkU4R6FC6Fw=,iv:s6wSg73xSp+qYkF4TLmThQqcsKW8tpMNEdcmkqb0el8=,tag:9BpYkMSMjbrrHZQ+3wz4aQ==,type:str]
    database-url: ENC[AES256_GCM,data:gLKvqlLbkWC/lh6TOV/jZjzb8HhA9SMCIUYJl9T/2cIb5CU6coYCBaY6k/FLGL+lceGFgURUtrZjr08ObqaaEAGWiVcp3tU=,iv:kvBSMne/GjVTnJbdAE9HGemvxRGiFa4kceVCFfPkOk4=,tag:kT+N/EFw5bER5OtixGKtVg==,type:str]
    hash-salt: ENC[AES256_GCM,data:ytHRYMxl2h4e1sPqmlVjuXcuwqebDO8P/ndsYtap0uWyhD3yLbdp+J/5sMg=,iv:FzwpcmsH75zZt/14gvk472W3m1xH7O4EgNpO7E4GOis=,tag:78TYIS9RfW8VXCD1DOJWmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1099kpzqp5v429mcyekxxnnyfkyuqxgq3esxvamc0kv7tf7nh9g9qymcpmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSDhOUVBWRHJpTkQ5OWdH
            ZjF2VkxoTGxrbnp2b0J2WDhjVmpoK3dXd1FzCnlUVFdnWUlhU01HdFc4b015Umdt
            Q1pUYUpiVVJ3NnIzeUFnbHo4bitmTmMKLS0tIDVNb0JXZ0g0L2Q4SWtFdGtWLyt6
            YmZXTmtINFBMeDN0bk1kcmxLNU9LSXMKHqEPtz+K2hpEfDnKWo6D36fl8hoVtAUs
            1+2h83ndLC+mEkbulh7uN3IrfQlTVAHSzFY6UFiI1qEg5nusD/nbrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-12T19:14:44Z"
    mac: ENC[AES256_GCM,data:N5pVAeqjpsrAa9BkF0vFPOJvHUz1Lhvgn2XWSxcQY17FNlYb59TzAjMpHDl7yxUmFo6Dx/rq4luj7LqQB8jqzx2DnI5LHxlOo47YXf49YaJXqWSyZM2fX8LHbMoaM+/PQECKdAHGvK6JPFoWMpEZt2UDKesXWFdNDEWI+i+zORs=,iv:ylKlAo9Raf8ZAQ4+0JeQykZhNPb26Z1E9vwWB8hexAE=,tag:uXDjQhB1aJNtT/HUZCi0xQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
