apiVersion: v1
kind: Secret
metadata:
    name: umami-config
    namespace: umami
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:aVZoe1fzKOVsjXTx5OZSj1HvKekQCh8LL6HIX7ApCXY=,iv:dCEWOq275rK7VRV9yKqPjHL51l2giPB7bLd49veDN84=,tag:y1fd4llgj62A6TybYIPa7Q==,type:str]
    database-url: ENC[AES256_GCM,data:7dIkqwBqk/qj5ul9dpvAMTq9GQ+wmoSuN8KPYHORMHbdp8vDM/Tux0llPqhue6Rx+uB/ZApJyFGKAamfC0Kq8TQXVhvTdbxR8ao=,iv:F9FgMZSUFvZJacs2G0qDvlnYM0RNQtaAiBvgJ50TrLI=,tag:SJetdWBthlM89mBHvIrMPA==,type:str]
    hash-salt: ENC[AES256_GCM,data:MfEZ7Pcwnc1laIXgM+2YHTVxmhTHgVRHVxByHLtP8MMZAD8ymphQwuB00fM=,iv:L8ljP+fwxhUgNzXe/z1CGCx55meFXwevM0h/a7wf53Q=,tag:ydrN373vtkXZTN3ljGAnww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1099kpzqp5v429mcyekxxnnyfkyuqxgq3esxvamc0kv7tf7nh9g9qymcpmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVVRpVmZrUVh5R1VPL2s1
            ZmJUSW9DVytNbGhaaHhUMU5zRDlHOGIrR2hjCm45aDN2VkY0a2RNMlJpWkIrcW5j
            NmxyZWMxUmxKTEVTWUd2Vks5cnZYUGsKLS0tIExCVXpRUHlqdGlSL1Y3S3VOcDZx
            MG1ha2lkNkphd2IyWU5ocTNYcG5lVUkKHnkkIJPVJFvmhfvX0Xc8WKw/h5P7rBEA
            uy9bBp/IJ/Z8CdsJ6n3EmQg+CjsC/W0HC1kkgwMT0SaardO765/qkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-12T19:11:34Z"
    mac: ENC[AES256_GCM,data:wCWaJbiQ2C1fJrIv3F3SLaF/JNSbsghWXElYFRv2bI1cevsjhd20Qr+VcX5moSwWACqWZIanaHi4affBDPX3BSa1UF7abMWxwIsfrHblmpOvsX8hZO8YMHimu/BFUuUi+pSbNSl9g/PlIh+eEhY+7VuE7XCpt9QZjvgGwHwlmZA=,iv:a8J/U/VNgifHpEfcdcIoeVQ4FZQ1YhOB1iZ2ImsPYBY=,tag:8NtzyFOzfDFiFhRKAE3CuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
