apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: selina
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" type="text/css" href="./default.css"/>
        <link rel="icon" href="https://sk-website-static.s3.eu-central-1.amazonaws.com/logo.ico">
        <title>Selina Klepi&#263</title>
      </head>
      <body>
        <div class="bgimg">
          <div class="middle">
            <h1>COMING SOON</h1>
            <hr>
            <img alt="Logo" src="https://sk-website-static.s3.eu-central-1.amazonaws.com/logo.png" width=250" oncontextmenu="return false">
          </div>
        </div>
      </body>
    </html>
  default.css: |
    @import url('https://fonts.googleapis.com/css?family=Roboto');
    /* Set height to 100% for body and html to enable the background image to cover the whole page: */
    body, html {
      font-family: 'Roboto', sans-serif;
      height: 100%;
      margin: 0;
      padding: 0;
    }

    .bgimg {
      /* Background image */
      background-image: url('https://sk-website-static.s3.eu-central-1.amazonaws.com/wallhaven-zxmd1g.jpg');
      /* Full-screen */
      height: 100%;
      /* Center the background image */
      background-position: center;
      /* Scale and zoom in the image */
      background-size: cover;
      /* Add position: relative to enable absolutely positioned elements inside the image (place text) */
      position: relative;
      /* Add a white text color to all elements inside the .bgimg container */
      color: white;
      /* Add a font */
      font-family: "Courier New", Courier, monospace;
      /* Set the font-size to 25 pixels */
      font-size: 25px;
    }

    /* Position text in the middle */
    .middle {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      text-align: center;
    }

    /* Style the <hr> element */
    hr {
      margin: auto;
      width: 40%;
    }
